services:
  db:
    image: mysql:8.0
    container_name: helloagent-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 789456112
      TZ: Asia/Shanghai
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_DATABASE: helloagent
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - yxp_agent_db_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    command: --default-time-zone='+8:00'

  app:
    build: .
    container_name: helloagent
    restart: always
    environment:
      - ENV=prod
      - TZ=Asia/Shanghai
    volumes:
      - /home/ubuntu/sys_agent/backend:/app
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  yxp_agent_db_data:
  
networks:
  default:
    name: milvus